# Generated by Django 5.2.8 on 2025-11-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Product_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=20)),
                ('Price', models.FloatField()),
                ('Manufacture_date', models.DateField()),
                ('Expiry_date', models.DateField()),
                ('Warranty', models.CharField(max_length=10)),
            ],
        ),
    ]
